#!/usr/bin/env ruby

require 'yaml'

domains = YAML.safe_load(File.read("data/domains.yaml"))
domains.uniq!

rules = domains.each_slice(75)
       .to_a
       .collect { |r| r.join(" OR ") }
puts rules

File.open("rules.yaml", "w") do |f|
  f.write(rules.to_yaml)
end

puts "---"
puts "Built #{rules.length} rules with #{domains.length} domains."